import Head from 'next/head'
import { Inter } from 'next/font/google'
import axios from 'axios'

const apiUrl = "https://api.jsonsilo.com/public/98c362fd-a701-4194-a845-6b2ddb7e733c"

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>JSON SILO [Sample]</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Example [Public]
      {data && data.map((v, k)=> (
        <div key={k}>
          <p>{v.name}</p>
          <p>{v.email}</p>
        </div>
        
      ))}
    </>
  )
}

export async function getServerSideProps() {
  try {

    // if you using NextJS api route uncomment this line
    // const response = await axios.get('http://localhost:3000/api/public');

    const response = await axios.get('https://api.jsonsilo.com/public/cd140031-5515-4e1c-aef5-d51fa6df021b');
    const data = await response.data;
    return {
      props: {
        data,
      },
    };
  } catch (error) {
    console.error('Error fetching data:', error.message);
    return {
      props: {
        data: null,
      },
    };
  }
}
